---
branches:
  only:
    - master
language: node_js
node_js:
  - "7.6.0"
  - "8.1.0"
cache:
  directories:
    - node_modules
before_install:
  - npm config set spin false
  - npm install -g codeclimate-test-reporter
install:
  - npm i .
script:
  - npm run cover
after_success:
  - npm run codeclimate_cov
  - npm run semantic-release
